const SANPHAM = [
    { 
        id: '1', 
        name: 'Thanh Gươm Diệt Quỷ',
        nametag: 'Kimetsu no Yaiba - Infinity Train',
        trailer: 'https://www.youtube.com/watch?v=oJf81IYInc8',
        nam: '2021', 
        categoryId:'1', 
        image: 'https://image.thanhnien.vn/1200x630/Uploaded/2022/ygtmjz/2020_11_24/thanh_guom_zfjf.jpg',
        cotTruyen: 'Vào thời xa xưa, có một truyền thuyết về những con quỷ ăn thịt người luôn lãng vãng trong cánh rừng sâu. Vì điều này, người dân trong làng không bao giờ đi ra ngoài vào trời tối. Truyền thuyến cũng kể rằng có một Sát Quỷ Nhân luôn xuất hiện vào ban đêm để tiêu diệt những con quỷ khát máu này. Đối với chàng trai trẻ Tanjiro, câu chuyện dân gian ấy đã trở thành hiện thực cay đắng mà cậu phải hứng chịu... Sau khi cha cậu qua đời, Tanjiro luôn cố gắng hết sức để trở thành trụ cột trong gia đình. Dù cuộc sống vất vả, cực khổ, những gia đình của cậu vẫn luôn ngập tràn hạnh phúc. Nhưng niềm hạnh phúc ấy cũng không kéo dài lâu được. Một ngày nọ, khi Tanjiro trở về, cậu phát hiện gia đình mình đã bị sát hại dã man, và chỉ có một người duy nhất sống sót, đó là em gái Nezuko của cậu. Nhưng bi kịch thay, Nezuko đã trở thành con quỷ đáng sợ. Tuy nhiên, cô vẫn còn giữ một chút nhân tính. Đó là thời điểm bắt đầu cuộc chiến đơn độc của Tanjiro, tiêu diệt quỷ và tìm cách biến em gái mình trở lại làm người.',
        color: 'red', 
        isFav: false, 
        isBrand: true, 
        isSale: true
    },
    { 
        id: '2', 
        name: 'Học Viện Anh Hùng',
        nametag: 'My Hero Academia',
        trailer: 'https://www.youtube.com/watch?v=PheMbfxCm-E',
        nam: '2021', 
        categoryId:'1', 
        image: 'https://static2.vieon.vn/vieplay-image/carousel_web_v4/2021/05/14/vitjn62d_1920x1080-hocvienanhhung2_1920_1080.jpg',
        cotTruyen: 'Anime Boku no Hero Academia là bộ phim xoay quanh Midoriya Izuku và con đường cậu trở thành siêu anh hùng mạnh nhất từ trước đến nay. Tuy nhiên, quá trình này không hề dễ dàng với một cậu nhóc sinh không có một chút siêu năng lực sống trong một thế giới ai cũng sở hữu năng lực đặc biệt.',
        color: 'red', 
        isFav: true, 
        isBrand: true, 
        isSale: true
    },
    { 
        id: '3', 
        name: 'Đấu Trường Ảo',
        nametag: 'READY PLAYER ONE',
        trailer: 'https://www.youtube.com/watch?v=FeX5YONWKA0',
        nam: '2018', 
        categoryId:'1', 
        image: 'https://static.ssphim.net/static/5fe2d564b3fa6403ffa11d1c/5fe2d564b3fa6478ffa12f9c_dau-truong-ao-1.jpg',
        cotTruyen: 'Phim Đấu Trường Ảo, Ready Player One (2018) : Phim Đấu Trường Ảo lấy bối cảnh năm 2044, khi người sáng lập ra Oasis - một tựa game online, mất mạng. Khi đó, ông thách thức tất cả những người chơi Oasis đi tìm Easter Eggs - Trứng phục sinh. Phần thưởng dành cho người chiến thắng là những tài sản vô cùng quý báu mà ông để lại. Một chàng trai mang tên Wade Watts đã tìm ra được những gợi ý đầu tiên trong cuộc tìm kiếm và bắt đầu hành trình của mình.',
        color: 'red', 
        isFav: true, 
        isBrand: true, 
        isSale: true
    },
    { 
        id: '4', 
        name: 'Biệt Đội Cảm Tử',
        nametag: 'Suicide Squad',
        trailer: 'https://www.youtube.com/watch?v=ht7hkZ2mZRo',
        nam: '2018', 
        categoryId:'1', 
        image: 'https://chonthuonghieu.com/wp-content/uploads/2021/07/The-Suicide-Squad.jpg',
        cotTruyen: 'Một nhóm những kẻ côn đồ tinh quái được tập hợp bởi cơ quan bí mật của chính phủ (A.R.G.U.S). Họ được giao thực hiện những nhiệm vụ nguy hiểm nhằm nhận được sự khoan hồng và cứu thế giới khỏi mối đe doạ bí ẩn',
        color: 'red', 
        isFav: true, 
        isBrand: true, 
        isSale: true
    },
    { 
        id: '5', 
        name: 'Nữ Thần Chiến Binh',
        nametag: 'WONDER WOMAN 1984',
        trailer: 'https://www.youtube.com/watch?v=Vk-gqL3c5qU',
        nam: '2020', 
        categoryId:'1', 
        image: 'https://thegioidienanh.vn/stores/news_dataimages/kimanh/062017/27/18/0811_MV5BM2RlOThkZWEtM2RkMi00MzllLThkMzktNWYyYThiOTQ3MjdhXkEyXkFqcGdeQXVyNjUwNzk3NDc._V1_.jpg',
        cotTruyen: 'Nữ Thần Chiến Binh 1984 - Wonder Woman 1984 kể về người phụ nữ Diana Prince một chiến binh, đầy tài giỏi và dũng cảm. Cô sẵn sàng đứng lên chiến đấu vì hòa bình của thế giới. Vào năm 80 cuộc chiến tranh lạnh của Mỹ và Liên Xô trở nên đầy căn thẳng, khốc liệt hơn, và sự xuất hiện của Cheetah khiến mọi chuyện trở nên nguy hiểm và đáng sợ hơn rất nhiều. Cheetah đang muốn thực hiện một âm mưu phá hủy thế giới, Diana đành phải làm mọi cách và sử dụng kỹ năng chiến đấu của mình ngăn chặn cuộc âm mưu này.',
        color: 'red', 
        isFav: true, 
        isBrand: true, 
        isSale: true
    },
    { 
        id: '6', 
        name: 'Alita: Thiên Thần Chiến Binh',
        nametag: 'ALITA: BATTLE ANGEL',
        trailer: 'https://www.youtube.com/watch?v=sx9dsNzIdGw',
        nam: '2019', 
        categoryId:'1', 
        image: 'https://cdnimg.vietnamplus.vn/t1200/Uploaded/pcfo/2019_02_22/2202_alitabattleangel.jpg',
        cotTruyen: 'Alita: Thiên Thần Chiến Binh Alita được ví như một thần chết đến từ địa ngục vì những khả năng vượt qua mọi giới hạn mà cô sở hữu. Cô được tìm thấy bởi Tiến sĩ Ido và không thể nhớ mình là ai hay từ đâu tới. Để có thể tìm ra sự thật, Atila phải dấn thân vào những cuộc chiến đấu nảy lửa.',
        color: 'red', 
        isFav: true, 
        isBrand: true, 
        isSale: true
    },
    { 
        id: '7', 
        name: 'Quái xế Baby',
        nametag: 'Baby Driver ',
        trailer: 'https://www.youtube.com/watch?v=SM9YGJ5If-Y',
        nam: '2017', 
        categoryId:'1', 
        image: 'https://rapchieuphim.com/photos/2/baby-driver/quai-xe-baby-mot-sieu-pham-hanh-dong-thuc-su-co-nao-4.jpg',
        cotTruyen: 'Phim Quái Xế Baby - Baby Driver (2017) Nội dung xoay quanh chàng tài xế tội phạm yêu âm nhạc thực hiện phi vụ cướp nhà băng cùng đồng bọn. Baby Driver là phép cộng hoàn hảo của một siêu phẩm hài hành động không thể bỏ lỡ trong năm 2017.',
        color: 'red', 
        isFav: true, 
        isBrand: true, 
        isSale: true
    },
    { 
        id: '8', 
        name: 'John Wick 3',
        nametag: 'John Wick',
        trailer: 'https://www.youtube.com/watch?v=pU8-7BX9uxs',
        nam: '2019', 
        categoryId:'1', 
        image: 'https://www.elleman.vn/wp-content/uploads/2018/12/02/phim-john-wick-elle-man-featured-image.jpeg',
        cotTruyen: 'Sát Thủ John Wick 3: Chuẩn Bị Chiến Tranh lấy bối cảnh sau sự kiện John Wick (Keanu Reeves) giết chết Santino D.Antonio (Riccardo Scamarcio) trong phần trước đó. Vì đã phá vỡ quy tắc của Continental (không được giết nhau trong khách sạn) nên John đã bị trục xuất và treo thưởng với cái đầu trị giá 14 triệu đô. Từ đây, hành trình chạy trốn của John trước sự săn đuổi của toàn bộ tội phạm trên thế giới bắt đầu.',
        color: 'red', 
        isFav: true, 
        isBrand: true, 
        isSale: true
    },
    { 
        id: '9', 
        name: 'Trò Chơi ảo Giác',
        nametag: 'Tron Legacy',
        trailer: 'https://www.youtube.com/watch?v=e1dHhktFLPs',
        nam: '2010', 
        categoryId:'1', 
        image: 'https://www.studyphim.vn/system/movies/1495/thumbnails/medium/1.png',
        cotTruyen: 'TRON: Legacy 2010 Phim Trò Chơi Ảo Ảnh là câu chuyện kể về Sam Flynn, một kỹ sư phần mềm 27 tuổi, con trai của chuyên gia công nghệ Kevin Flynn, trong cuộc tìm kiếm người cha mất tích của mình. Sam đã bị kéo vào thế giới ảo được tạo ra bởi phần mềm điện tử, nơi cha anh đã sống trong 25 năm qua. Với sự giúp đỡ trung thành của Quorra, cuộc phiêu lưu ngoạn mục của hai cha con bắt đầu qua một thế giới đặc biệt công nghệ cao và đặc biệt nguy hiểm. Từng được so sánh với Avatar, Phim Tron: Legacy là một siêu phẩm hấp dẫn đối với những khán giả trung thành của dòng phim 3D.',
        color: 'red', 
        isFav: true, 
        isBrand: true, 
        isSale: true
    },
    { 
        id: '10', 
        name: 'Chuyến Tàu Băng Giá',
        nametag: 'SNOWPIERCER',
        trailer: 'https://www.youtube.com/watch?v=RbrkbBMbXYM',
        nam: '2014', 
        categoryId:'1', 
        image: 'https://media-cdn.laodong.vn/storage/newsportal/2020/4/6/796166/Chuyen-Tau-Bang-Gia-.jpg?w=720&crop=auto&scale=both',
        cotTruyen: 'Năm 2014, trước vấn nạn Trái Đất đang nóng lên, các nhà lãnh đạo trên toàn thế giới đã quyết định tung lên bầu khí quyển vật chất CW-7, nhằm giúp nhiệt độ trung bình của địa cầu ổn định trở lại. Thế nhưng kết quả mà loài người thu được thì thật kinh hoàng: toàn bộ thế giới bị đóng băng, sự sống cứ thế dần tuyệt diệt. Chỉ có duy nhất một con tàu có tên Snowpiercer do Ngài Wilford cầm lái vẫn cứ thế lầm lũi chạy xuyên băng tuyết, chở trên đó những kẻ sót lại cuối cùng của nhân loại...',
        color: 'red', 
        isFav: true, 
        isBrand: true, 
        isSale: true
    },
    { 
        id: '11', 
        name: 'Kẻ Đâm Lén',
        nametag: 'Knives Out',
        trailer: 'https://www.youtube.com/watch?v=oJf81IYInc8',
        nam: '2019', 
        categoryId:'2', 
        image: 'https://i.ytimg.com/vi/PdHlnVZV6Gc/maxresdefault.jpg',
        cotTruyen: 'Kẻ Đâm Lén là bộ phim kể về nhân dịp sinh nhật lần thứ 85 của mình, tiểu thuyết gia trinh thám nổi tiếng Harlan Thombrey đã tổ chức một buổi tiệc với đông đủ các thành viên trong gia đình. Tuy nhiên, ông Harlan bất ngờ qua đời ngay trong ngày hôm đấy. Thám tử Benoit Blanc được cử đến để điều tra vụ án và tất cả mọi người trong gia đình đều trở thành nghi phạm. Vậy trong ngôi nhà nhiều thế hệ này, ai mới chính là Kẻ Đâm Lén?',
        color: 'red', 
        isFav: true, 
        isBrand: true, 
        isSale: true
    },
    { 
        id: '12', 
        name: 'Cô Gái Trên Tàu',
        nametag: 'The Girl on the Train',
        trailer: 'https://www.youtube.com/watch?v=5xABUJtpQUk',
        nam: '2016', 
        categoryId:'2', 
        image: 'https://znews-photo.zadn.vn/w660/Uploaded/xbhunku/2017_03_02/002.jpg',
        cotTruyen: 'Nhân vật chính của câu chuyện là Rachel Watson. Cô là một người lái tàu, hàng ngày cô đưa mọi người di chuyển trên con tàu của mình và ngắm nhìn những ánh đèn ấm áp nơi ngoại ô hay cảm nhận sự hạnh phúc của các đôi vợ chồng. Đối với Rachel cuộc sống của họ thật hoàn hảo, chẳng giống như cuộc sống mà cô đã mất',
        color: 'red', 
        isFav: true, 
        isBrand: true, 
        isSale: true
    },
    { 
        id: '13', 
        name: 'Lần Theo Dấu Vết',
        nametag: 'Prisoners',
        trailer: 'hhttps://www.youtube.com/watch?v=wCjy-EtBVk8',
        nam: '2013', 
        categoryId:'2', 
        image: 'http://phimchieurap.gdy.vn/wp-content/uploads/2020/12/lantheodauvet2013prisoners.jpg',
        cotTruyen: 'Kể về một người thợ mộc ở một thị trấn nhỏ, tên là Keller Dover (do Hugh Jackman thủ vai). Sau khi đứa con gái sáu tuổi cùng với người bạn thân nhất của mình bị bắt cóc vào ngày Lễ Tạ Ơn, Dover đối đầu với thám tử Loki (doJake Gyllenhaal thủ vai), một thám tử trẻ tuổi và ngông nghênh chịu trách nhiệm điều tra vụ này. Kelly Dover phải đối mặt với cơn ác mộng tồi tệ nhất của bậc làm cha mẹ, khi mà mỗi phút trôi qua, sự nguy hiểm đối với con gái của mình càng tăng.',
        color: 'red', 
        isFav: true, 
        isBrand: true, 
        isSale: true
    },
    { 
        id: '14', 
        name: 'Tội Ác Ngủ Say',
        nametag: 'Go To Sleep',
        trailer: 'https://www.youtube.com/watch?v=F_PWVFOzPLI',
        nam: '2014', 
        categoryId:'2', 
        image: 'https://image.tmdb.org/t/p/w1280//Qf366kUqyfGkB7Q3vqlB8I0VIR.jpg',
        cotTruyen: 'Tội Ác Ngủ Say kể về Christine Lucas là một phụ nữ đã bị mất đi trí nhớ sau một vụ tấn công đầy bạo lực nhiều năm về trước. Mỗi ngày thức dậy với Christine là một ngày đầy ắp những hoang mang khi cô chỉ nhớ được những việc xảy ra trong vòng 24 giờ hoặc trước khi cô trôi vào một giấc ngủ sâu. Cuộc hành trình đi tìm lại những ngày hôm qua để tố cáo kẻ thủ ác đã hãm hại cô không gớm tay có được sự trợ giúp của người chồng và vị bác sĩ điều trị cho Christine. Nhưng rồi một ngày cô bàng hoàng nhận ra rằng, người duy nhất cô có thể tin tưởng là không ai khác ngoài chính bản thân mình…',
        color: 'red', 
        isFav: true, 
        isBrand: true, 
        isSale: true
    },
    { 
        id: '15', 
        name: 'Số 23 bí ẩn',
        nametag: 'The Number 23 ',
        trailer: 'https://www.youtube.com/watch?v=kxfPfrP8gjc',
        nam: '2014', 
        categoryId:'2', 
        image: 'http://1.bp.blogspot.com/-mmlNbNsY7A0/VC1XaW_oUeI/AAAAAAAATNM/3Qn37c_LD0c/s1600/The-Number-23-2007-1.jpg',
        cotTruyen: 'Trong phim Số 23 Bí Ẩn, Walter Sparrow là nhân viên bắt chó chạy rông với cô vợ yêu chồng và cậu con trai ngoan ngoãn. Xem phim này bạn sẽ thấy anh có một cuộc sống phẳng lặng và yên bình cho tới khi anh phát hiện ra một cuốn tiểu thuyết kỳ lạ,',
        color: 'red', 
        isFav: true, 
        isBrand: true, 
        isSale: true
    },
    { 
        id: '16', 
        name: 'Truy Lùng Siêu Trộm',
        nametag: 'COLD EYES',
        trailer: 'https://www.youtube.com/watch?v=3cck8Mzv5FY',
        nam: '2013', 
        categoryId:'2', 
        image: 'https://static.fptplay.net/static/img/share/video/19_11_2020/united19-11-2020_07g46-17.jpg',
        cotTruyen: 'Cold Eyes sở hữu tựa đề Việt là Truy Lùng Siêu Trộm, là một phim thuộc thể dòng hành động hình sự của điện ảnh Hàn Quốc được công chiếu vào năm 2013. Phim được chỉ đạo nội dung bởi cặp đôi đạo diễn Ui-seok Jo và Byung-seo Kim và là một phiên bản khiến lại của bộ phim Hồng Kông Eye in the Sky, cùng sự tham gia của dàn diễn viên đình đám như Hyo-ju Han, Kyung Jin, Woo-sung Jung, Dong-Hwi Lee,…',
        color: 'red', 
        isFav: true, 
        isBrand: true, 
        isSale: true
    },
    { 
        id: '17', 
        name: 'Tội Ác Xoay Vòng',
        nametag: 'Chronicles of Evil',
        trailer: 'https://www.youtube.com/watch?v=7Ha4Tk-_MSQ',
        nam: '2007', 
        categoryId:'2', 
        image: 'http://1.bp.blogspot.com/-PVtu-Qc3LxU/VQKB5K1nUPI/AAAAAAAAAow/WTs74Tx4BRc/s1600/Timecrimes-2007-2.jpg',
        cotTruyen: 'Hector is an ordinary man who s moving to a new house with his wife. One evening, while he s looking through his binoculars, he sees a naked girl in the woods. He decides to go there just to find that same girl laying on a rock. Suddenly, a man with a pink bandage covering his face, stabs Hector in his arm with scissors...',
        color: 'red', 
        isFav: true, 
        isBrand: true, 
        isSale: true
    },
    { 
        id: '18', 
        name: 'Thám Tử Sherlock Holmes',
        nametag: 'Sherlock Holmes',
        trailer: 'https://www.youtube.com/watch?v=RURmUzKftEc',
        nam: '2012', 
        categoryId:'2', 
        image: 'https://cdnimg.vietnamplus.vn/uploaded/pcfo/2017_02_02/0202_sherlock_holmes.jpg',
        cotTruyen: 'Trong phim Thám Tử Sherlock Holmes, hàng loạt vụ giết đã người xảy ra, thám tử đại tài Sherlock Holmes cùng trợ tá đắc lực của mình bác sĩ John Watson quyết định điều tra về tên giết người dưới vỏ bọc tôn giáo Lord Henry Blackwood. ',
        color: 'red', 
        isFav: true, 
        isBrand: true, 
        isSale: true
    },
    { 
        id: '19', 
        name: 'Án Mạng Trên Sông Nile',
        nametag: 'Death On The Nile',
        trailer: 'https://www.youtube.com/watch?v=24z2KnQvaOQ',
        nam: '2022', 
        categoryId:'2', 
        image: 'https://cdnimg.vietnamplus.vn/uploaded/ivpycivo/2022_02_14/image.jpeg',
        cotTruyen: '',
        color: 'red', 
        isFav: true, 
        isBrand: true, 
        isSale: true
    },
    { 
        id: '20', 
        name: 'Mê cung ký ức',
        nametag: 'Trance',
        trailer: 'https://www.youtube.com/watch?v=yaNRM9MX61M',
        nam: '2013', 
        categoryId:'2', 
        image: 'https://baocantho.com.vn/image/news/2014/20140328/fckimage/25191498114227_102.jpg',
        cotTruyen: 'Phim  Mê Cung Ký Ức  Trance  Full HD thuyết minh thôi miên khán giả vào một cuộc thử thách gay cấn, hấp dẫn cả về hình ảnh, diễn xuất và âm nhạc. Một cốt truyện đơn giản song nếu rơi vào tay một nhà làm phim giỏi thì vẫn có khả năng cuốn hút khán giả từ đầu đến cuối.',
        color: 'red', 
        isFav: true, 
        isBrand: true, 
        isSale: true
    },{ 
        id: '21', 
        name: 'Đừng Nghe',
        nametag: 'Dont Listen',
        trailer: 'https://www.youtube.com/watch?v=TYDBwdLFU7I',
        nam: '2020', 
        categoryId:'3', 
        image: 'https://static.ssphim.net/static/5fe2d564b3fa6403ffa11d1c/5fe2d564b3fa648445a12f91_voces-1.jpg',
        cotTruyen: 'Không phải bộ phim kinh dị nào cũng cần những cảnh giật gân, máu me rợn người. Bộ phim Đừng nghe - Dont Listen (Voces) là bộ phim mới nhất của Netflix trong loạt các phim được công chiếu trên kênh trực tuyến mà không có quá nhiều sự phô trương. ',
        color: 'red', 
        isFav: true, 
        isBrand: true, 
        isSale: true
    },
    { 
        id: '22', 
        name: 'Đảo Kinh Hoàng',
        nametag: 'FANTASY ISLAND',
        trailer: 'https://www.youtube.com/watch?v=VQLzBHx2CUk',
        nam: '2020', 
        categoryId:'3', 
        image: 'https://ghienreview.com/wp-content/uploads/2020/02/Ghien-review-Dao-kinh-hoang-4-1024x576.jpg',
        cotTruyen: 'Đảo Kinh Hoàng là câu chuyện về quý ngài Roarke và trợ lý Tatto, chào mừng các vị khách đến hòn đảo biệt lập của mình, và hứa hẹn 1 cuộc sống như họ mong ước, nhưng ước mơ nào cũng có cái giá của nó.',
        color: 'red', 
        isFav: true, 
        isBrand: true, 
        isSale: true
    },
    { 
        id: '23', 
        name: 'Ấn Quỷ',
        nametag: 'The Unholy',
        trailer: 'https://www.youtube.com/watch?v=f1Nv2O7VJuo',
        nam: '2021', 
        categoryId:'3', 
        image: 'https://image.thanhnien.vn/w660/Uploaded/2022/kbfluau/2021_04_01/the-unholy_alqg.jpg',
        cotTruyen: 'Ấn Quỷ - The Unholy là bộ phim thuộc thể loại kinh dị siêu nhiên của Mỹ do đạo diễn Evan Spiliotopoulos viết kịch bản đồng sản xuất và chỉ đạo, dựa trên cuốn tiểu thuyết được phát hành vào năm 1983 - Shrine của James Herbert. Bộ phim được sản xuất bởi Sam Raimi với nhà sản xuất Ghost House Pictures, tác phẩm có sự tham gia của các diễn viên Jeffrey Dean Morgan, Katie Aselton, William Sadler, Diogo Morgado, Cricket Brown, Cary Elwes.',
        color: 'red', 
        isFav: true, 
        isBrand: true, 
        isSale: true
    },
    { 
        id: '24', 
        name: 'Già',
        nametag: 'Old',
        trailer: 'https://www.youtube.com/watch?v=bMT3RVAf_aE',
        nam: '2021', 
        categoryId:'3', 
        image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRpOK-Q1r8YPH0NyBN4lLzuKPfuiIUO3Vlz4hl0uV39T6TLDVeobCpEgOymPhwvt17FNk0&usqp=CAU',
        cotTruyen: 'Bộ phim theo chân bốn nhóm người lạ đi nghỉ cùng nhau, họ tới nghỉ dưỡng tại một bãi biển riêng đặc biệt của khu nghỉ mát, và họ chợt nhận ra có điều gì đó rất kỳ lạ. Một gia đình bốn người gồm bố hi họ nhận ra rằng có điều gì đó không thể sửa chữa được. Một gia đình bốn người - bố Guy (Gael García Bernal), mẹ Prisca (Vicky Krieps), Maddox 11 tuổi (Alexa Swinton) và Trent 6 tuổi (Nolan) tới khu nghỉ mát nhiệt đới ở một vị trí không xác định.',
        color: 'red', 
        isFav: true, 
        isBrand: true, 
        isSale: true
    },
    { 
        id: '25', 
        name: 'Annabella: Ác Quỷ Trở Về',
        nametag: 'ANNABELLE COMES HOME',
        trailer: 'https://www.youtube.com/watch?v=Rm-jr2XHr1M',
        nam: '2019', 
        categoryId:'3', 
        image: 'https://vnn-imgs-f.vgcloud.vn/2019/06/17/17/bup-be-annabelle-da-san-sang-hu-doa-khan-gia.jpg',
        cotTruyen: 'Annabelle: Ác Quỷ Trở Về là bộ phim kểv ề sau những sự kiện xưa, vợ chồng pháp sư trừ tà Warren đưa Annabelle về nhà và niêm phong nó trong một căn phòng đặc biệt. Một ngày nọ trong lúc vợ chồng Warren rời khỏi nhà để thực hiện một nhiệm vụ bí ẩn, cơn ác mộng thực sự bắt đầu khi người bạn Daniela của Mary Ellen - bảo mẫu nhà Warren tò mò khám phá căn phòng đầy những món đồ quỷ ám và vô tình giải thoát cho Annabelle. Từ đó, Annabelle dẫn dắt các linh hồn khác có trong căn phòng cùng trỗi dậy, với mục tiêu mới nhằm vào chính Judy  cô con gái nhà Warren và bạn bè của cô bé',
        color: 'red', 
        isFav: true, 
        isBrand: true, 
        isSale: true
    },
    { 
        id: '26', 
        name: 'Xác Chết Quỷ Ám',
        nametag: 'THE POSSESSION OF HANNAH GRACE',
        trailer: 'https://www.youtube.com/watch?v=0w7z__r_jfw',
        nam: '2018', 
        categoryId:'3', 
        image: 'https://channel.mediacdn.vn/thumb_w/640/2018/12/22/photo-1-1545456432852457995219.jpg',
        cotTruyen: 'Xác Chết Quỷ Ám kể về Megan Reed (Shay Mitchell) là một nữ bác sĩ có vấn đề về tâm lý nên luôn cần sự hỗ trợ của thuốc an thần trong những ca trực đêm tại nhà xác trong bệnh viện. Một ngày nọ, cô nhận được xác chết nhăn nhúm của Hannah Grace (Kirby Johnson) - người được cho là đã chết sau một buổi trừ tà thất bại.',
        color: 'red', 
        isFav: true, 
        isBrand: true, 
        isSale: true
    },
    { 
        id: '27', 
        name: 'Căn phòng Tử Thần',
        nametag: 'Escape Room',
        trailer: 'https://www.youtube.com/watch?v=La3g6VNgag4',
        nam: '2019', 
        categoryId:'3', 
        image: 'https://3.bp.blogspot.com/-y5bDk47yHT4/XIXsTe3Pc0I/AAAAAAABOVw/OIDaYiUbB18Xike1g15JRMPtbQrRYNckACLcBGAs/s1600/C%25C4%2583n%2BPh%25C3%25B2ng%2BT%25E1%25BB%25AD%2BTh%25E1%25BA%25A7n%2B-%2BEscape%2BRoom%2B%25282019%2529.jpg',
        cotTruyen: 'Căn phòng tử thần Sáu người từ các hoàn cảnh khác nhau được giới thiệu với một khối xếp hình : Zoey, một sinh viên vật lý; Jason, một người buôn bán ban ngày giàu có; Ben, một người chơi cổ phiếu; Mike, một tài xế xe tải; Amanda, một cựu chiến binh Chiến tranh Iraq ; và Danny, một người đam mê phòng thoát hiểm . ',
        color: 'red', 
        isFav: true, 
        isBrand: true, 
        isSale: true
    },
    { 
        id: '28', 
        name: 'Lồng Chim',
        nametag: 'Bird Box',
        trailer: 'https://www.youtube.com/watch?v=o2AsIXSh2xo',
        nam: '2018', 
        categoryId:'3', 
        image: 'https://kenh14cdn.com/thumb_w/660/2018/10/25/photo-1-1540438962765805382813.jpg',
        cotTruyen: 'Lồng Chim - Bird Box chuyện gì sẽ xảy ra nếu cả thế giới rơi vào nguy kịch trước sự tấn công bởi những con quái vật mà chưa một ai từng thấy hình dạng? Sẽ đáng sợ ra sao nếu chúng sơ sẩy một tích tắc nhìn vào chúng, và rồi chúng ta phát điên lên, tự huỷ sự sống của bản thân? Với cách duy nhất để sống sót là bịt mắt và trốn chạy, Malorie phải làm mọi cách để giữ hai con an toàn giữa cuộc chiến trong bóng tối. Không chỉ phải chiến đấu với những con quái vật vô hình, cô còn phải đấu tranh với bản thân khi chỉ cần một lần hé nhìn là có thể mất đi ánh sáng mãi mãi.',
        color: 'red', 
        isFav: true, 
        isBrand: true, 
        isSale: true
    },
    { 
        id: '29', 
        name: 'It',
        nametag: 'IT',
        trailer: 'https://www.youtube.com/watch?v=xKJmEC5ieOk',
        nam: '2017', 
        categoryId:'3', 
        image: 'https://vtv1.mediacdn.vn/thumb_w/650/2019/6/25/pennywise-voice-changer-min-15614392003941999426148.png',
        cotTruyen: 'Chú hề ma quái là một bộ phim kinh dị siêu nhiên Mỹ ra mắt năm 2017 của đạo diễn Andy Muschietti. Đây là phần đầu tiên trong kế hoạch sản xuất loạt phim It hai phần dựa trên cuốn tiểu thuyết cùng tên của nhà văn Stephen King. Nhóm biên kịch của phim gồm có Chase Palmer, Cary Fukunaga và Gary Dauberman.',
        color: 'red', 
        isFav: false, 
        isBrand: true, 
        isSale: true
    },
    { 
        id: '30', 
        name: 'Ma Búp Bê 5',
        nametag: 'Chucky Childs Play 5: Seed of Chucky',
        trailer: 'https://www.youtube.com/watch?v=oJf81IYInc8',
        nam: '2004', 
        categoryId:'3', 
        image: 'https://doanhnhanplus.vn/wp-content/uploads/2020/02/Chucky.png',
        cotTruyen: 'Phần 5 của loạt phim về con búp bê giết người. Con của Chucky và Tiffany bị thất lạc bên Anh, trong khi hai bố mẹ thì chết sau phần 4. Hollywood thì đang dựng bộ phim về Chucky, với nữ diễn viên Jennifer Tilly đóng chính. Búp bê con bèn đến Hollywood và vô tình làm sống lại đôi búp bê giết người đáng sợ. Nhưng ngược lại với phụ huynh, búp bê con lại không thích giết chóc, và là một người tốt bụng… Chucky quyết định huấn luyện cho con mình trở thành một tên giết người hàng loạt.',
        color: 'red', 
        isFav: true, 
        isBrand: true, 
        isSale: true
    },{ 
        id: '31', 
        name: 'Cuộc chiến ngày mai',
        nametag: 'The Tomorrow War',
        trailer: 'https://www.youtube.com/watch?v=QPistcpGB8o',
        nam: '2021', 
        categoryId:'4', 
        image: 'https://n-cdn.serienjunkies.de/hq/107379.jpg',
        cotTruyen: 'Một người đàn ông của gia đình chiến đấu trong cuộc chiến tương lai, nơi số phận của nhân loại dựa vào khả năng đối đầu với quá khứ của anh',
        color: 'red', 
        isFav: true, 
        isBrand: true, 
        isSale: true
    },
    { 
        id: '32', 
        name: 'Tiệt Chủng',
        nametag: 'Extinct',
        trailer: 'https://static.vphimzz.net/img/vpreview-IbvT1xe.jpg',
        nam: '2018', 
        categoryId:'4', 
        image: 'https://static.vphimzz.net/img/vpreview-IbvT1xe.jpg',
        cotTruyen: 'Phim tuyệt chủng Extinction Peter, một kỹ sư, có những cơn ác mộng lặp đi lặp lại, trong đó anh và mọi người anh biết phải chịu đựng những cuộc đối đầu bạo lực, giống như cuộc xâm lược của người ngoài hành tinh với kẻ thù không xác định. Điều này khiến anh ta có một mối quan hệ căng thẳng với vợ mình, Alice, và các con gái của anh ta là Hanna và Lucy. Anh ta miễn cưỡng đến một phòng khám để nhận trợ giúp tâm thần, chỉ để tìm một bệnh nhân ở đó tiết lộ rằng anh ta đang có những tầm nhìn tương tự, và psychs sẽ chỉ ngăn chặn những tầm nhìn này.',
        color: 'red', 
        isFav: true, 
        isBrand: true, 
        isSale: true
    },
    { 
        id: '33', 
        name: 'Đấu Trường Ảo',
        nametag: 'READY PLAYER ONE',
        trailer: 'https://www.youtube.com/watch?v=FeX5YONWKA0',
        nam: '2018', 
        categoryId:'4', 
        image: 'https://static.ssphim.net/static/5fe2d564b3fa6403ffa11d1c/5fe2d564b3fa6478ffa12f9c_dau-truong-ao-1.jpg',
        cotTruyen: 'Phim Đấu Trường Ảo, Ready Player One (2018) : Phim Đấu Trường Ảo lấy bối cảnh năm 2044, khi người sáng lập ra Oasis - một tựa game online, mất mạng. Khi đó, ông thách thức tất cả những người chơi Oasis đi tìm Easter Eggs - Trứng phục sinh. Phần thưởng dành cho người chiến thắng là những tài sản vô cùng quý báu mà ông để lại. Một chàng trai mang tên Wade Watts đã tìm ra được những gợi ý đầu tiên trong cuộc tìm kiếm và bắt đầu hành trình của mình.',
        color: 'red', 
        isFav: true, 
        isBrand: true, 
        isSale: true
    },
    { 
        id: '34', 
        name: 'Siêu Đại Chiến',
        nametag: 'Pacific Rim',
        trailer: 'https://www.youtube.com/watch?v=6Fcy8Ua74SA',
        nam: 'red', 
        categoryId:'4', 
        image: 'https://static.ssphim.net/static/5fe2d564b3fa6403ffa11d1c/602e2b75781ca16f4ec6b7d4_pacific-rim-1.jpg',
        cotTruyen: 'Siêu đại chiến thái bình dương - Pacific Rim là bộ phim điện ảnh lấy đề tài khoa học viễn tưởng và quái vật của Mỹ được phát hành năm 2013 do Guillermo del Toro chịu trách nhiệm chỉ đạo, với sự tham gia của dàn diễn viên gồm Charlie Hunnam, Idris Elba, Kikuchi Rinko, Charlie Day...',
        color: 'red', 
        isFav: true, 
        isBrand: true, 
        isSale: true
    },
    { 
        id: '35', 
        name: 'Hố Sâu Đói Khát',
        nametag: 'The Platform',
        trailer: 'https://www.youtube.com/watch?v=98ayZLHkW_M',
        nam: '2019', 
        categoryId:'4', 
        image: 'https://ghienreview.com/wp-content/uploads/2020/03/Ghien-review-Ho-sau-doi-khat-03.jpg',
        cotTruyen: 'Khi tù nhân tầng trên tham lam ăn hết đồ ngon, những kẻ tầng dưới chỉ còn một chút cơm thừa canh cạn. Vậy phải làm sao để ai cũng đủ đồ ăn? Hắn sẽ ra tay hành động.',
        color: 'red', 
        isFav: true, 
        isBrand: true, 
        isSale: true
    },
    { 
        id: '36', 
        name: 'Alita: Thiên Thần Chiến Binh',
        nametag: 'ALITA: BATTLE ANGEL',
        trailer: 'https://www.youtube.com/watch?v=sx9dsNzIdGw',
        nam: '2019', 
        categoryId:'4', 
        image: 'https://cdnimg.vietnamplus.vn/t1200/Uploaded/pcfo/2019_02_22/2202_alitabattleangel.jpg',
        cotTruyen: 'Alita: Thiên Thần Chiến Binh Alita được ví như một thần chết đến từ địa ngục vì những khả năng vượt qua mọi giới hạn mà cô sở hữu. Cô được tìm thấy bởi Tiến sĩ Ido và không thể nhớ mình là ai hay từ đâu tới. Để có thể tìm ra sự thật, Atila phải dấn thân vào những cuộc chiến đấu nảy lửa.',
        color: 'red', 
        isFav: true, 
        isBrand: true, 
        isSale: true
    },
    { 
        id: '37', 
        name: 'Siêu Báo Địa Cầu',
        nametag: 'Geostorm',
        trailer: 'https://www.youtube.com/watch?v=hzqHtC040P4',
        nam: '2017', 
        categoryId:'4', 
        image: 'https://imgs.vietnamnet.vn/Images/2017/10/12/15/20171012153723-1.jpeg',
        cotTruyen: 'Phim Siêu Bão Địa Cầu khi con người đã phải chịu quá nhiều thiên tai, bão lũ, với trình độ khoa học siêu tiên tiến, các nhà lãnh đạo cấp cao hàng đầu thế giới đã quyết định xây dựng một vệ tinh cao cấp có khả năng điều khiển thời tiết, kiểm soát khí hậu toàn cầu để giảm thiểu tối đa những thiệt hại về người và của cho con người.',
        color: 'red', 
        isFav: true, 
        isBrand: true, 
        isSale: true
    },
    { 
        id: '38', 
        name: 'Đại chiến hành tinh khỉ',
        nametag: 'War for the Planet of the Apes',
        trailer: 'https://www.youtube.com/watch?v=NH51gfV7Fx4',
        nam: 'red', 
        categoryId:'4', 
        image: 'https://channel.mediacdn.vn/thumb_w/640/prupload/164/2017/07/img20170712192611793.jpg',
        cotTruyen: 'Những sai lầm trầm trọng của y học khiến loài khỉ phát triển vượt bậc, xây dựng nên một đế chế như con người. Sau những cuộc chiến khốc liệt của các phần trước, loài người và loài khỉ sẽ giáp mặt trong trận chiến cuối cùng đen tối nhất và đẫm máu nhất.',
        color: 'red', 
        isFav: true, 
        isBrand: true, 
        isSale: true
    },
    { 
       id: '39', 
        name: 'Trò Chơi ảo Giác',
        nametag: 'Tron Legacy',
        trailer: 'https://www.youtube.com/watch?v=e1dHhktFLPs',
        nam: '2010', 
        categoryId:'4', 
        image: 'https://www.studyphim.vn/system/movies/1495/thumbnails/medium/1.png',
        cotTruyen: 'TRON: Legacy 2010 Phim Trò Chơi Ảo Ảnh là câu chuyện kể về Sam Flynn, một kỹ sư phần mềm 27 tuổi, con trai của chuyên gia công nghệ Kevin Flynn, trong cuộc tìm kiếm người cha mất tích của mình. Sam đã bị kéo vào thế giới ảo được tạo ra bởi phần mềm điện tử, nơi cha anh đã sống trong 25 năm qua. Với sự giúp đỡ trung thành của Quorra, cuộc phiêu lưu ngoạn mục của hai cha con bắt đầu qua một thế giới đặc biệt công nghệ cao và đặc biệt nguy hiểm. Từng được so sánh với Avatar, Phim Tron: Legacy là một siêu phẩm hấp dẫn đối với những khán giả trung thành của dòng phim 3D.',
        color: 'red', 
        isFav: true, 
        isBrand: true, 
        isSale: true
    },
    { 
        id: '40', 
        name: 'Chuyến Tàu Băng Giá',
        nametag: 'SNOWPIERCER',
        trailer: 'https://www.youtube.com/watch?v=RbrkbBMbXYM',
        nam: '2014', 
        categoryId:'4', 
        image: 'https://media-cdn.laodong.vn/storage/newsportal/2020/4/6/796166/Chuyen-Tau-Bang-Gia-.jpg?w=720&crop=auto&scale=both',
        cotTruyen: 'Năm 2014, trước vấn nạn Trái Đất đang nóng lên, các nhà lãnh đạo trên toàn thế giới đã quyết định tung lên bầu khí quyển vật chất CW-7, nhằm giúp nhiệt độ trung bình của địa cầu ổn định trở lại. Thế nhưng kết quả mà loài người thu được thì thật kinh hoàng: toàn bộ thế giới bị đóng băng, sự sống cứ thế dần tuyệt diệt. Chỉ có duy nhất một con tàu có tên Snowpiercer do Ngài Wilford cầm lái vẫn cứ thế lầm lũi chạy xuyên băng tuyết, chở trên đó những kẻ sót lại cuối cùng của nhân loại...',
        color: 'red', 
        isFav: true, 
        isBrand: true, 
        isSale: true
    },
];
export default SANPHAM;