const SANPHAMS = [
    {   id: '1', 
        name: 'Thanh Gươm Diệt Quỷ',
        mota: 'Kimetsu no Yaiba là một bộ truyện tranh Nhật Bản của tác giả Gotōge Koyoharu. Bộ truyện tranh này đã được đăng theo kỳ trên Weekly Shōnen Jump từ số phát hành tháng 2 năm 2016 đến tháng 5 năm 2020 và sau đó các chương truyện được tổng hợp đưa vào 21 cuốn tankōbon',
        daoDien:'Đang Cập Nhật',
        quocGia: 'Nhật Bản',
        Nam: '2019',
        ngonNgu: 'Phụ đề việt',
        theLoai: 'Hài Hước, Hành Động, Hoạt Hình, Phiêu Lưu, Phim Bộ, Thần Thoại',
        color: 'red', 
        categoryId:'1', 
        image: 'https://static.ssphim.net/static/5fe2d564b3fa6403ffa11d1c/5fe2d564b3fa6447e2a12fa2_chuyen-tau-vo-tan-1.jpg', 
        isFav: true, isBrand: true, isSale: true
    },

    {   id: '2', 
        name: 'Học Viện Anh Hùng',
        daoDien:'Đang Cập Nhật',
        quocGia: 'Nhật Bản',
        Nam: '2021',
        ngonNgu: 'Phụ đề việt',
        theLoai: 'Hành Động',
        color: 'red', 
        categoryId:'1', 
        image: 'https://static.247phim.com/160223/conversions/6008ffd643fd9_hvah-s1-1-435_627.jpg', 
        isFav: true, isBrand: true, isSale: true
    },
 
    {   id: '3', 
        name: 'Đấu Trường Ảo',
        daoDien:'Steven Spielberg',
        quocGia: 'Mỹ',
        Nam: '2018',
        ngonNgu: 'Phụ đề việt',
        theLoai: 'Hành Động ,Phiêu Lưu, Viễn Tưởng',
        color: 'red', 
        categoryId:'1', 
        image: 'https://upload.wikimedia.org/wikipedia/vi/3/3b/%C4%90%E1%BA%A5u_tr%C6%B0%E1%BB%9Dng_%E1%BA%A3o_2018.jpg', 
        isFav: true, isBrand: true, isSale: true
    },

    {   id: '4', 
        name: 'Biệt Đội Cảm Tử',
        daoDien:'David Ayer',
        quocGia: 'Mỹ',
        Nam: '2016',
        ngonNgu: 'Phụ đề việt',
        theLoai: 'Hành Động',
        color: 'red', 
        categoryId:'1', 
        image: 'https://upload.wikimedia.org/wikipedia/vi/1/16/Bi%E1%BB%87t_%C4%91%E1%BB%99i_c%E1%BA%A3m_t%E1%BB%AD.jpg', 
        isFav: true, isBrand: true, isSale: true
    },
 
    {   id: '5', 
        name: 'Nữ Thần Chiến Binh',
        daoDien:'Patty Jenkins',
        quocGia: 'Mỹ',
        Nam: '2017',
        ngonNgu: 'Phụ đề việt',
        theLoai: 'Hành Động, Viễn Tưởng',
        color: 'red', 
        categoryId:'1', 
        image: 'https://upload.wikimedia.org/wikipedia/vi/e/ed/Wonder_Woman_%282017_film%29.jpg', 
        isFav: true, isBrand: true, isSale: true
    },

    {   id: '6', 
        name: 'Alita: Thiên Thần Chiến Binh',
        daoDien:'Robert Rodriguez',
        quocGia: 'Âu Mỹ',
        Nam: '2019',
        ngonNgu: 'Phụ đề việt',
        theLoai: 'Hành Động, Viễn Tưởng, Phiêu Lưu, Chiến Tranh',
        color: 'red', 
        categoryId:'1', 
        image: 'https://upload.wikimedia.org/wikipedia/vi/d/d2/Alita_Thi%C3%AAn_th%E1%BA%A7n_chi%E1%BA%BFn_binh_%28%C3%A1p_ph%C3%ADch_2019%29.jpg', 
        isFav: true, isBrand: true, isSale: true
    },

    {   id: '7', 
        name: 'Quái xế Baby',
        daoDien:'Edgar Wright',
        quocGia: 'Âu Mỹ',
        Nam: '2017',
        ngonNgu: 'Phụ đề việt',
        theLoai: 'Hành Động, Hài Hước',
        color: 'red', 
        categoryId:'1', 
        image: 'https://upload.wikimedia.org/wikipedia/vi/8/8e/Baby_Driver_poster.jpg', 
        isFav: true, isBrand: true, isSale: true
    },

    {   id: '8', 
        name: 'John Wick 3',
        daoDien:'Chad Stahelski',
        quocGia: 'Âu Mỹ',
        Nam: '2019',
        ngonNgu: 'Phụ đề việt',
        theLoai: 'Hành Động',
        color: 'red', 
        categoryId:'1', 
        image: 'https://upload.wikimedia.org/wikipedia/vi/3/32/John_Wick_3_Parabellum_bia_poster.jpg', 
        isFav: true, isBrand: true, isSale: true
    },
 
    {   id: '9', 
        name: 'Trò Chơi ảo Giác',
        daoDien:'Joseph Kosinski',
        quocGia: 'Mỹ',
        Nam: '2010',
        ngonNgu: 'Phụ đề việt',
        theLoai: 'Hành Động, Viễn Tưởng',
        color: 'red', 
        categoryId:'1', 
        image: 'https://upload.wikimedia.org/wikipedia/vi/thumb/c/c2/Tron_Legacy_poster.jpg/220px-Tron_Legacy_poster.jpg', 
        isFav: true, isBrand: true, isSale: true
    },

    {   id: '10', 
        name: 'Chuyến Tàu Băng Giá',
        daoDien:'Joon ho Bong',
        quocGia: 'Mỹ',
        Nam: '2014',
        ngonNgu: 'Phụ đề việt',
        theLoai: 'Hành Động, Viễn Tưởng',
        color: 'red', 
        categoryId:'1', 
        image: 'https://upload.wikimedia.org/wikipedia/vi/2/29/Poster_phim_Chuy%E1%BA%BFn_t%C3%A0u_b%C4%83ng_gi%C3%A1_2014.jpg', 
        isFav: true, isBrand: true, isSale: true
    },
    
    {   id: '11', 
        name: 'Kẻ Đâm Lén',
        daoDien:'Rian Johnson',
        quocGia: 'Âu Mỹ',
        Nam: '2019',
        ngonNgu: 'Phụ đề việt',
        theLoai: 'Trinh Thám',
        color: 'red', 
        categoryId:'2', 
        image: 'https://upload.wikimedia.org/wikipedia/vi/d/d2/%C3%81p_ph%C3%ADch_K%E1%BA%BB_%C4%91%C3%A2m_l%C3%A9n.jpg', 
        isFav: true, isBrand: true, isSale: true
    },

    {   id: '12', 
        name: 'Cô Gái Trên Tàu',
        daoDien:'Tate Taylor',
        quocGia: 'Mỹ',
        Nam: '2016',
        ngonNgu: 'Phụ đề việt',
        theLoai: 'Trinh Thám',
        color: 'red', 
        categoryId:'2', 
        image: 'https://znews-photo.zadn.vn/w660/Uploaded/xbhunku/2017_03_02/Main_Poster_1__Co_Gai_Tren_Tau.jpg', 
        isFav: true, isBrand: true, isSale: true
    },
 
    {   id: '13', 
        name: 'Lần Theo Dấu Vết',
        daoDien:'Denis Villeneuve',
        quocGia: 'Mỹ',
        Nam: '2013',
        ngonNgu: 'Phụ đề việt',
        theLoai: 'Trinh Thám',
        color: 'red', 
        categoryId:'2', 
        image: 'https://upload.wikimedia.org/wikipedia/vi/thumb/c/c2/L%E1%BA%A7n_theo_d%E1%BA%A5u_v%E1%BA%BFt_poster.jpg/220px-L%E1%BA%A7n_theo_d%E1%BA%A5u_v%E1%BA%BFt_poster.jpg', 
        isFav: true, isBrand: true, isSale: true
    },

    {   id: '14', 
        name: 'Tội Ác Ngủ Say',
        daoDien:'Rowan Joffe',
        quocGia: 'Anh',
        Nam: '2014',
        ngonNgu: 'Phụ đề việt',
        theLoai: 'Trinh Thám',
        color: 'red', 
        categoryId:'2', 
        image: 'https://upload.wikimedia.org/wikipedia/vi/3/35/Poster_phim_T%E1%BB%99i_%C3%A1c_ng%E1%BB%A7_say_2014.jpg', 
        isFav: true, isBrand: true, isSale: true
    },
 
    {   id: '15', 
        name: 'Số 23 Bí Ẩn',
        daoDien:'Joel Schumacher',
        quocGia: 'Mỹ',
        Nam: '2014',
        ngonNgu: 'Phụ đề việt',
        theLoai: 'Trinh Thám',
        color: 'red', 
        categoryId:'2', 
        image: 'https://afamilycdn.com/Images/Uploaded/Share/2009/04/09/2005370095024320393rs.jpg', 
        isFav: true, isBrand: true, isSale: true
    },

    {   id: '16', 
        name: 'Truy Lùng Siêu Trộm',
        daoDien:'Byung-seo Kim',
        quocGia: 'Hàn Quốc',
        Nam: '2013',
        ngonNgu: 'Phụ đề việt',
        theLoai: 'Trinh Thám',
        color: 'red', 
        categoryId:'2', 
        image: 'https://static2.vieon.vn/vieplay-image/poster_v4/2021/01/05/j0ctz1zk_truy-lung-sieu-trom_vertical-thumbnail-png_360_534.jpg', 
        isFav: true, isBrand: true, isSale: true
    },

    {   id: '17', 
        name: 'Tội Ác Xoay Vòng',
        daoDien:'Nacho Vigalondo',
        quocGia: 'Châu âu',
        Nam: '3007',
        ngonNgu: 'Phụ đề việt',
        theLoai: 'Trinh Thám',
        color: 'red', 
        categoryId:'2', 
        image: 'https://static.247phim.com/128289/conversions/5700_timecrimes-2007_photo_portrait-435_627.jpg', 
        isFav: true, isBrand: true, isSale: true
    },

    {   id: '18', 
        name: 'Thám Tử Sherlock Holmes',
        daoDien:'Guy Ritchie',
        quocGia: 'Mỹ',
        Nam: '2012',
        ngonNgu: 'Phụ đề việt',
        theLoai: 'Trinh Thám',
        color: 'red', 
        categoryId:'2', 
        image: 'https://thegioidienanh.vn/stores/news_dataimages/thanhtan/052021/03/15/in_article/0636_image0012.jpg?rt=20210503150706', 
        isFav: true, isBrand: true, isSale: true
    },
 
    {   id: '19', 
        name: 'Án Mạng Trên Sông Nile',
        daoDien:'Kenneth Branagh',
        quocGia: 'Mỹ',
        Nam: '2022',
        ngonNgu: 'Phụ đề việt',
        theLoai: 'Trinh Thám',
        color: 'red', 
        categoryId:'2', 
        image: 'https://upload.wikimedia.org/wikipedia/vi/thumb/b/b7/%C3%81p_ph%C3%ADch_phim_%C3%81n_m%E1%BA%A1ng_tr%C3%AAn_s%C3%B4ng_Nile.jpg/220px-%C3%81p_ph%C3%ADch_phim_%C3%81n_m%E1%BA%A1ng_tr%C3%AAn_s%C3%B4ng_Nile.jpg', 
        isFav: true, isBrand: true, isSale: true
    },

    {   id: '20', 
        name: 'Mê Cung Ký Ức',
        daoDien:'Danny Boyle',
        quocGia: 'Mỹ',
        Nam: '2013',
        ngonNgu: 'Phụ đề việt',
        theLoai: 'Trinh Thám, Hành Động',
        color: 'red', 
        categoryId:'2', 
        image: 'https://static.247phim.com/135718/conversions/5ea26bd216663_trance_d-435_627.jpg', 
        isFav: true, isBrand: true, isSale: true
    },

    {   id: '21', 
        name: 'Dont Listen',
        daoDien:'Angel Gómez Hernández',
        quocGia: 'Nga',
        Nam: '2020',
        ngonNgu: 'Phụ đề việt',
        theLoai: 'Kinh Dị',
        color: 'red', 
        categoryId:'3', 
        image: 'https://m.media-amazon.com/images/M/MV5BMmM5MGUzZTctNTQzZC00NGFjLWI4ZDYtZWRhMWY5Zjk3YTU2XkEyXkFqcGdeQXVyMTA0MjU0Ng@@._V1_.jpg', 
        isFav: true, isBrand: true, isSale: true
    },

    {   id: '22', 
        name: 'Đảo Kinh Hoàng',
        daoDien:'Jeff Wadlow',
        quocGia: 'Mỹ',
        Nam: '2020',
        ngonNgu: 'Phụ đề việt',
        theLoai: 'Kinh Dị',
        color: 'red', 
        categoryId:'3', 
        image: 'https://upload.wikimedia.org/wikipedia/vi/7/7e/Fantasy_Island_poster.jpg', 
        isFav: true, isBrand: true, isSale: true
    },
 
    {   id: '23', 
        name: 'Ấn Quỷ',
        daoDien:'Evan Spiliotopoulos',
        quocGia: 'Mỹ',
        Nam: '2021',
        ngonNgu: 'Phụ đề việt',
        theLoai: 'Kinh Dị',
        color: 'red', 
        categoryId:'3', 
        image: 'https://upload.wikimedia.org/wikipedia/vi/f/fc/%E1%BA%A4n_qu%E1%BB%B7_poster.jpeg', 
        isFav: true, isBrand: true, isSale: true
    },

    {   id: '24', 
        name: 'Già',
        daoDien:'M. Night Shyamalan',
        quocGia: 'Mỹ',
        Nam: '2021',
        ngonNgu: 'Phụ đề việt',
        theLoai: 'Kinh Dị',
        color: 'red', 
        categoryId:'3', 
        image: 'https://cdnmedia.thethaovanhoa.vn/Upload/O5NP4aFt6GVwE7JTFAOaA/files/2021/05/OLD-gia-phim%20(1).jpg', 
        isFav: true, isBrand: true, isSale: true
    },
 
    {   id: '25', 
        name: 'Annabella: Ác Quỷ Trở Về',
        daoDien:'Gary Dauberman',
        quocGia: 'Mỹ',
        Nam: '2019',
        ngonNgu: 'Phụ đề việt',
        theLoai: 'Kinh Dị',
        color: 'red', 
        categoryId:'3', 
        image: 'https://static.247phim.com/149828/conversions/5f2a6d32d318b_annabelle-02-435_627.jpg', 
        isFav: true, isBrand: true, isSale: true
    },

    {   id: '26', 
        name: 'Xác Chết Quỷ Ám',
        daoDien:'Diederik Van Rooijen,',
        quocGia: 'Mỹ',
        Nam: '2018',
        ngonNgu: 'Phụ đề việt',
        theLoai: 'Kinh Dị',
        color: 'red', 
        categoryId:'3', 
        image: 'https://khenphim.com/wp-content/uploads/2018/12/xac-chet-quy-am-3-poster.jpg', 
        isFav: true, isBrand: true, isSale: true
    },

    {   id: '27', 
        name: 'Căn phòng Tử Thần',
        daoDien:'Adam Robitel',
        quocGia: 'Mỹ',
        Nam: '2019',
        ngonNgu: 'Phụ đề việt',
        theLoai: 'Kinh Dị',
        color: 'red', 
        categoryId:'3', 
        image: 'https://upload.wikimedia.org/wikipedia/vi/thumb/5/5a/C%C4%83n_ph%C3%B2ng_t%E1%BB%AD_th%E1%BA%A7n_poster.jpg/220px-C%C4%83n_ph%C3%B2ng_t%E1%BB%AD_th%E1%BA%A7n_poster.jpg', 
        isFav: true, isBrand: true, isSale: true
    },

    {   id: '28', 
        name: 'Lồng Chim',
        daoDien:'Susanne Bier',
        quocGia: 'Mỹ',
        Nam: '2018',
        ngonNgu: 'Phụ đề việt',
        theLoai: 'Kinh Dị',
        color: 'red', 
        categoryId:'3', 
        image: 'https://static.247phim.com/131661/conversions/7440_bird-box-2018_photo_portrait-435_627.jpg', 
        isFav: true, isBrand: true, isSale: true
    },
 
    {   id: '29', 
        name: 'IT',
        daoDien:'Andrés Muschietti',
        quocGia: 'Âu Mỹ',
        Nam: '2017',
        ngonNgu: 'Phụ đề việt',
        theLoai: 'Kinh Dị',
        color: 'red', 
        categoryId:'3', 
        image: 'https://kenh14cdn.com/thumb_w/660/2017/9fc1804344088752cc83e05eb84bd166-1504583687958.jpg', 
        isFav: true, isBrand: true, isSale: true
    },

    {   id: '30', 
        name: 'Ma Búp Bê 5',
        daoDien:'Don Mancini',
        quocGia: 'Mỹ',
        Nam: '2004',
        ngonNgu: 'Phụ đề việt',
        theLoai: 'Kinh Dị',
        color: 'red', 
        categoryId:'3', 
        image: 'https://image.bongngocdn.com/upload/poster_ma-bup-be-5.jpg', 
        isFav: true, isBrand: true, isSale: true
    },

    {   id: '31', 
        name: 'The Tomorrow War',
        daoDien: 'Chris McKay',
        quocGia: 'Mỹ',
        Nam: '2021',
        ngonNgu: 'Phụ đề việt',
        theLoai: 'Viễn Tưởng',
        color: 'red', 
        categoryId:'4', 
        image: 'https://phimnhua.com/wp-content/uploads/2021/07/cuoc-chien-tuong-lai-tomorrow-war-2021.jpg', 
        isFav: true, isBrand: true, isSale: true
    },

    {   id: '32', 
        name: 'Tiệt Chủng',
        daoDien:'Ben Young',
        quocGia: 'Mỹ',
        Nam: '2018',
        ngonNgu: 'Phụ đề việt',
        theLoai: 'Viễn Tưởng',
        color: 'red', 
        categoryId:'4', 
        image: 'https://phimnhua.com/wp-content/uploads/2021/11/extinction_2018-270x400.jpg', 
        isFav: true, isBrand: true, isSale: true
    },
 
    {   id: '33', 
        name: 'Đấu Trường Ảo',
        daoDien:'Steven Spielberg',
        quocGia: 'Mỹ',
        Nam: '2018',
        ngonNgu: 'Phụ đề việt',
        theLoai: 'Hành Động ,Phiêu Lưu, Viễn Tưởng',
        color: 'red', 
        categoryId:'4', 
        image: 'https://upload.wikimedia.org/wikipedia/vi/3/3b/%C4%90%E1%BA%A5u_tr%C6%B0%E1%BB%9Dng_%E1%BA%A3o_2018.jpg', 
        isFav: true, isBrand: true, isSale: true
    },

    {   id: '34', 
        name: 'Siêu Đại Chiến',
        daoDien:'Guillermo del Toro',
        quocGia: 'Mỹ',
        Nam: '2013',
        ngonNgu: 'Phụ đề việt',
        theLoai: 'Viễn Tưởng',
        color: 'red', 
        categoryId:'4', 
        image: 'https://static.247phim.com/130199/conversions/6665_pacific-rim-2013_photo_portrait-435_627.jpg', 
        isFav: true, isBrand: true, isSale: true
    },
 
    {   id: '35', 
        name: 'Hố Sâu Đói Khát',
        daoDien:'Galder Gaztelu-Urrutia',
        quocGia: 'Tây Ban Nha',
        Nam: '2019',
        ngonNgu: 'Phụ đề việt',
        theLoai: 'Viễn Tưởng',
        color: 'red', 
        categoryId:'4', 
        image: 'https://ragus.vn/wp-content/uploads/2020/03/The-Platform-H%E1%BB%91-s%C3%A2u-%C4%91%C3%B3i-kh%C3%A1t-2019-full-hd-vietsub-5-scaled.jpg', 
        isFav: true, isBrand: true, isSale: true
    },

    {   id: '36', 
        name: 'Alita: Thiên Thần Chiến Binh',
        daoDien:'Robert Rodriguez',
        quocGia: 'Âu Mỹ',
        Nam: '2019',
        ngonNgu: 'Phụ đề việt',
        theLoai: 'Hành Động, Viễn Tưởng, Phiêu Lưu, Chiến Tranh',
        color: 'red', 
        categoryId:'4', 
        image: 'https://upload.wikimedia.org/wikipedia/vi/d/d2/Alita_Thi%C3%AAn_th%E1%BA%A7n_chi%E1%BA%BFn_binh_%28%C3%A1p_ph%C3%ADch_2019%29.jpg', 
        isFav: true, isBrand: true, isSale: true
    },

    {   id: '37', 
        name: 'Siêu Báo Địa Cầu',
        daoDien:' Dean Devlin',
        quocGia: 'Mỹ',
        Nam: '2017',
        ngonNgu: 'Phụ đề việt',
        theLoai: 'Viễn Tưởng',
        color: 'red', 
        categoryId:'4', 
        image: 'https://upload.wikimedia.org/wikipedia/vi/0/05/Si%C3%AAu_b%C3%A3o_%C4%91%E1%BB%8Ba_c%E1%BA%A7u_poster.jpg', 
        isFav: true, isBrand: true, isSale: true
    },

    {   id: '38', 
        name: 'Đại Chiến Hành Tinh Khỉ',
        daoDien:'Matt Reeves',
        quocGia: 'Mỹ',
        Nam: '2017',
        ngonNgu: 'Phụ đề việt',
        theLoai: 'Viễn Tưởng',
        color: 'red', 
        categoryId:'4', 
        image: 'https://upload.wikimedia.org/wikipedia/vi/d/d0/%C4%90%E1%BA%A1i_chi%E1%BA%BFn_h%C3%A0nh_tinh_kh%E1%BB%89_poster.jpg', 
        isFav: true, isBrand: true, isSale: true
    },
 
    {   id: '39', 
        name: 'Trò Chơi ảo Giác',
        daoDien:'Joseph Kosinski',
        quocGia: 'Mỹ',
        Nam: '2010',
        ngonNgu: 'Phụ đề việt',
        theLoai: 'Hành Động, Viễn Tưởng',
        color: 'red', 
        categoryId:'4', 
        image: 'https://upload.wikimedia.org/wikipedia/vi/thumb/c/c2/Tron_Legacy_poster.jpg/220px-Tron_Legacy_poster.jpg', 
        isFav: true, isBrand: true, isSale: true
    },

    {   id: '40', 
        name: 'Chuyến Tàu Băng Giá',
        daoDien:'Joon ho Bong',
        quocGia: 'Mỹ',
        Nam: '2014',
        ngonNgu: 'Phụ đề việt',
        theLoai: 'Hành Động, Viễn Tưởng',
        color: 'red', 
        categoryId:'4', 
        image: 'https://upload.wikimedia.org/wikipedia/vi/2/29/Poster_phim_Chuy%E1%BA%BFn_t%C3%A0u_b%C4%83ng_gi%C3%A1_2014.jpg', 
        isFav: true, isBrand: true, isSale: true
    },
];
export default SANPHAMS;